######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 9 14:11:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
QT += xml

# Input
HEADERS += src/Alignment.h \
           src/AlignmentView.h \
           src/AnnotationView.h \
           src/BlockStatusBar.h \
           src/BlockView.h \
           src/BlockViewMain.h \
           src/BlockViewMap.h \
           src/DrawingArea.h \
           src/FilterControl.h \
           src/LcbView.h \
           src/LinkedSplitter.h \
           src/MainWindow.h \
           src/NameListView.h \
           src/OptionButton.h \
           src/OptionPanel.h \
           src/PhylogenyNode.h \
           src/PhylogenyTree.h \
           src/PhylogenyTreeStatusBar.h \
           src/PhylogenyTreeView.h \
           src/PhylogenyTreeViewMain.h \
           src/PhylogenyTreeViewMap.h \
           src/ReferenceView.h \
           src/Region.h \
           src/RegionView.h \
           src/RulerView.h \
           src/SnpBuffer.h \
           src/SnpWorker.h \
           src/StatusBar.h \
           src/StatusLabel.h \
           src/Timer.h \
           src/Track.h \
           src/TrackListView.h \
           src/TrackView.h \
           src/Tween.h
SOURCES += src/Alignment.cpp \
           src/AlignmentView.cpp \
           src/AnnotationView.cpp \
           src/BlockStatusBar.cpp \
           src/BlockView.cpp \
           src/BlockViewMain.cpp \
           src/BlockViewMap.cpp \
           src/DrawingArea.cpp \
           src/FilterControl.cpp \
           src/LcbView.cpp \
           src/LinkedSplitter.cpp \
           src/main.cpp \
           src/MainWindow.cpp \
           src/NameListView.cpp \
           src/OptionButton.cpp \
           src/OptionPanel.cpp \
           src/PhylogenyNode.cpp \
           src/PhylogenyTree.cpp \
           src/PhylogenyTreeStatusBar.cpp \
           src/PhylogenyTreeView.cpp \
           src/PhylogenyTreeViewMain.cpp \
           src/PhylogenyTreeViewMap.cpp \
           src/ReferenceView.cpp \
           src/Region.cpp \
           src/RegionView.cpp \
           src/RulerView.cpp \
           src/SnpBuffer.cpp \
           src/SnpWorker.cpp \
           src/StatusBar.cpp \
           src/StatusLabel.cpp \
           src/Timer.cpp \
           src/Track.cpp \
           src/TrackListView.cpp \
           src/TrackView.cpp \
           src/Tween.cpp
