######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 18 14:56:19 2013
######################################################################

TEMPLATE = app
DEPENDPATH += . src
INCLUDEPATH += . src $$quote(/usr/local/include/) $$quote(/opt/homebrew/include/)
QT += xml
QT += widgets

!wasm {
    QT += concurrent
}

CONFIG += release
!wasm {
    LIBS += /usr/local/lib/libharvest_no_main.a /opt/homebrew/lib/libprotobuf.dylib /opt/homebrew/lib/libcapnp.a /opt/homebrew/lib/libkj.a -lz -L/opt/homebrew/lib -labsl_base -labsl_log_internal_message -labsl_log_internal_check_op -labsl_log_internal_nullguard -labsl_strings -labsl_throw_delegate
}
RESOURCES += resource.qrc
ICON = img/gingr.icns
QMAKE_CXXFLAGS += -std=c++11

unix {
	macx {
		TARGET = Gingr
		LIBS += -mmacosx-version-min=10.7 -stdlib=libc++
		QMAKE_CXXFLAGS += -mmacosx-version-min=10.7 -stdlib=libc++
	} else: !wasm {
		TARGET = gingr
		LIBS += -L. -static-libstdc++ -Wl,--wrap=memcpy
		QMAKE_CXXFLAGS += -include src/memcpyLink.h -D_GNU_SOURCE
		QMAKE_CFLAGS += -include src/memcpyLink.h
	}
}

wasm {
	TARGET = gingr
}

# Input
HEADERS += src/Alignment.h \
           src/AlignmentView.h \
           src/AnnotationView.h \
           src/BaseBuffer.h \
           src/BaseImage.h \
           src/BlockStatusBar.h \
           src/BlockView.h \
           src/BlockViewMain.h \
           src/BlockViewMap.h \
           src/CodonTable.h \
           src/DrawingArea.h \
           src/FileInput.h \
           src/FilterControl.h \
		   src/ImportWindow.h \
           src/LcbView.h \
           src/LinkedSplitter.h \
           src/MainWindow.h \
           src/NameListView.h \
           src/OptionButton.h \
           src/OptionPanel.h \
           src/PhylogenyTreeStatusBar.h \
           src/PhylogenyTreeView.h \
           src/PhylogenyTreeViewMain.h \
           src/PhylogenyTreeViewMap.h \
           src/ReferenceView.h \
           src/Region.h \
           src/RegionView.h \
           src/RulerView.h \
           src/SearchControl.h \
           src/SnapshotWindow.h \
           src/SnpBuffer.h \
           src/SnpData.h \
           src/SnpLegend.h \
           src/SnpPalette.h \
           src/SnpWorker.h \
           src/StatusBar.h \
           src/StatusLabel.h \
		   src/SyntenyPalette.h \
           src/Timer.h \
           src/Track.h \
           src/TrackHeightController.h \
           src/TrackListView.h \
           src/TrackView.h \
           src/Tween.h \
           src/ColumnConservationView.h
SOURCES += src/Alignment.cpp \
           src/AlignmentView.cpp \
           src/AnnotationView.cpp \
           src/BaseBuffer.cpp \
           src/BaseImage.cpp \
           src/BlockStatusBar.cpp \
           src/BlockView.cpp \
           src/BlockViewMain.cpp \
           src/BlockViewMap.cpp \
           src/CodonTable.cpp \
           src/DrawingArea.cpp \
		   src/FileInput.cpp \
           src/FilterControl.cpp \
           src/ImportWindow.cpp \
           src/LcbView.cpp \
           src/LinkedSplitter.cpp \
           src/main.cpp \
           src/MainWindow.cpp \
           src/memcpyWrap.c \
           src/NameListView.cpp \
           src/OptionButton.cpp \
           src/OptionPanel.cpp \
           src/PhylogenyTreeStatusBar.cpp \
           src/PhylogenyTreeView.cpp \
           src/PhylogenyTreeViewMain.cpp \
           src/PhylogenyTreeViewMap.cpp \
           src/ReferenceView.cpp \
           src/Region.cpp \
           src/RegionView.cpp \
           src/RulerView.cpp \
           src/SearchControl.cpp \
           src/SnapshotWindow.cpp \
           src/SnpBuffer.cpp \
           src/SnpData.cpp \
           src/SnpLegend.cpp \
           src/SnpPalette.cpp \
           src/SnpWorker.cpp \
           src/StatusBar.cpp \
           src/StatusLabel.cpp \
		   src/SyntenyPalette.cpp \
           src/Timer.cpp \
           src/Track.cpp \
           src/TrackHeightController.cpp \
           src/TrackListView.cpp \
           src/TrackView.cpp \
           src/Tween.cpp \
           src/ColumnConservationView.cpp
