#############################################################################
# Makefile for building: gavqt.app/Contents/MacOS/gavqt
# Generated by qmake (2.01a) (Qt 4.8.3) on: Tue Apr 9 14:12:17 2013
# Project:  gavqt.pro
# Template: app
# Command: /usr/bin/qmake -o gavqt.xcodeproj/project.pbxproj gavqt.pro
#############################################################################

MOC       = /Developer/Tools/Qt/moc
UIC       = /Developer/Tools/Qt/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-xcode -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/usr/include -I. -Isrc -I. -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers -F/Library/Frameworks
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./moc_AlignmentView.cpp ./moc_AnnotationView.cpp ./moc_BlockView.cpp\
	 ./moc_BlockViewMain.cpp ./moc_BlockViewMap.cpp ./moc_DrawingArea.cpp\
	 ./moc_FilterControl.cpp ./moc_LinkedSplitter.cpp ./moc_MainWindow.cpp\
	 ./moc_NameListView.cpp ./moc_OptionButton.cpp ./moc_OptionPanel.cpp\
	 ./moc_PhylogenyTreeView.cpp ./moc_PhylogenyTreeViewMain.cpp ./moc_PhylogenyTreeViewMap.cpp\
	 ./moc_RulerView.cpp ./moc_SnpBuffer.cpp ./moc_SnpWorker.cpp\
	 ./moc_StatusBar.cpp ./moc_TrackListView.cpp
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_AlignmentView.cpp moc_AnnotationView.cpp moc_BlockView.cpp moc_BlockViewMain.cpp moc_BlockViewMap.cpp moc_DrawingArea.cpp moc_FilterControl.cpp moc_LinkedSplitter.cpp moc_MainWindow.cpp moc_NameListView.cpp moc_OptionButton.cpp moc_OptionPanel.cpp moc_PhylogenyTreeView.cpp moc_PhylogenyTreeViewMain.cpp moc_PhylogenyTreeViewMap.cpp moc_RulerView.cpp moc_SnpBuffer.cpp moc_SnpWorker.cpp moc_StatusBar.cpp moc_TrackListView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AlignmentView.cpp moc_AnnotationView.cpp moc_BlockView.cpp moc_BlockViewMain.cpp moc_BlockViewMap.cpp moc_DrawingArea.cpp moc_FilterControl.cpp moc_LinkedSplitter.cpp moc_MainWindow.cpp moc_NameListView.cpp moc_OptionButton.cpp moc_OptionPanel.cpp moc_PhylogenyTreeView.cpp moc_PhylogenyTreeViewMain.cpp moc_PhylogenyTreeViewMap.cpp moc_RulerView.cpp moc_SnpBuffer.cpp moc_SnpWorker.cpp moc_StatusBar.cpp moc_TrackListView.cpp
moc_AlignmentView.cpp: src/Alignment.h \
		src/Region.h \
		src/TrackListView.h \
		src/DrawingArea.h \
		src/TrackView.h \
		src/RegionView.h \
		src/Tween.h \
		src/AlignmentView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/AlignmentView.h -o moc_AlignmentView.cpp

moc_AnnotationView.cpp: src/DrawingArea.h \
		src/Alignment.h \
		src/Region.h \
		src/AnnotationView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/AnnotationView.h -o moc_AnnotationView.cpp

moc_BlockView.cpp: src/Alignment.h \
		src/Region.h \
		src/TrackListView.h \
		src/DrawingArea.h \
		src/Tween.h \
		src/Timer.h \
		src/SnpBuffer.h \
		src/BlockView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/BlockView.h -o moc_BlockView.cpp

moc_BlockViewMain.cpp: src/BlockView.h \
		src/Alignment.h \
		src/Region.h \
		src/TrackListView.h \
		src/DrawingArea.h \
		src/Tween.h \
		src/Timer.h \
		src/SnpBuffer.h \
		src/BlockViewMain.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/BlockViewMain.h -o moc_BlockViewMain.cpp

moc_BlockViewMap.cpp: src/BlockView.h \
		src/Alignment.h \
		src/Region.h \
		src/TrackListView.h \
		src/DrawingArea.h \
		src/Tween.h \
		src/Timer.h \
		src/SnpBuffer.h \
		src/BlockViewMap.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/BlockViewMap.h -o moc_BlockViewMap.cpp

moc_DrawingArea.cpp: src/DrawingArea.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/DrawingArea.h -o moc_DrawingArea.cpp

moc_FilterControl.cpp: src/OptionPanel.h \
		src/Tween.h \
		src/Timer.h \
		src/Alignment.h \
		src/Region.h \
		src/FilterControl.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/FilterControl.h -o moc_FilterControl.cpp

moc_LinkedSplitter.cpp: src/LinkedSplitter.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/LinkedSplitter.h -o moc_LinkedSplitter.cpp

moc_MainWindow.cpp: src/PhylogenyTreeView.h \
		src/TrackListView.h \
		src/DrawingArea.h \
		src/PhylogenyTree.h \
		src/PhylogenyNode.h \
		src/Track.h \
		src/Region.h \
		src/NameListView.h \
		src/AlignmentView.h \
		src/Alignment.h \
		src/TrackView.h \
		src/RegionView.h \
		src/Tween.h \
		src/AnnotationView.h \
		src/BlockViewMain.h \
		src/BlockView.h \
		src/Timer.h \
		src/SnpBuffer.h \
		src/BlockViewMap.h \
		src/RulerView.h \
		src/BlockStatusBar.h \
		src/StatusLabel.h \
		src/PhylogenyTreeStatusBar.h \
		src/MainWindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/MainWindow.h -o moc_MainWindow.cpp

moc_NameListView.cpp: src/DrawingArea.h \
		src/PhylogenyTree.h \
		src/PhylogenyNode.h \
		src/Track.h \
		src/Region.h \
		src/NameListView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/NameListView.h -o moc_NameListView.cpp

moc_OptionButton.cpp: src/OptionPanel.h \
		src/Tween.h \
		src/Timer.h \
		src/OptionButton.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/OptionButton.h -o moc_OptionButton.cpp

moc_OptionPanel.cpp: src/Tween.h \
		src/Timer.h \
		src/OptionPanel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/OptionPanel.h -o moc_OptionPanel.cpp

moc_PhylogenyTreeView.cpp: src/TrackListView.h \
		src/DrawingArea.h \
		src/PhylogenyTree.h \
		src/PhylogenyNode.h \
		src/Track.h \
		src/Region.h \
		src/PhylogenyTreeView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/PhylogenyTreeView.h -o moc_PhylogenyTreeView.cpp

moc_PhylogenyTreeViewMain.cpp: src/PhylogenyTreeView.h \
		src/TrackListView.h \
		src/DrawingArea.h \
		src/PhylogenyTree.h \
		src/PhylogenyNode.h \
		src/Track.h \
		src/Region.h \
		src/PhylogenyTreeViewMain.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/PhylogenyTreeViewMain.h -o moc_PhylogenyTreeViewMain.cpp

moc_PhylogenyTreeViewMap.cpp: src/PhylogenyTreeView.h \
		src/TrackListView.h \
		src/DrawingArea.h \
		src/PhylogenyTree.h \
		src/PhylogenyNode.h \
		src/Track.h \
		src/Region.h \
		src/PhylogenyTreeViewMap.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/PhylogenyTreeViewMap.h -o moc_PhylogenyTreeViewMap.cpp

moc_RulerView.cpp: src/DrawingArea.h \
		src/Alignment.h \
		src/Region.h \
		src/RulerView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/RulerView.h -o moc_RulerView.cpp

moc_SnpBuffer.cpp: src/Alignment.h \
		src/Region.h \
		src/SnpBuffer.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/SnpBuffer.h -o moc_SnpBuffer.cpp

moc_SnpWorker.cpp: src/Alignment.h \
		src/Region.h \
		src/SnpWorker.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/SnpWorker.h -o moc_SnpWorker.cpp

moc_StatusBar.cpp: src/StatusBar.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/StatusBar.h -o moc_StatusBar.cpp

moc_TrackListView.cpp: src/DrawingArea.h \
		src/TrackListView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/TrackListView.h -o moc_TrackListView.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

